#pragma once

#define SGE_STR(x) #x
#define SGE_STRINGIFY_MACRO(x) SGE_STR(x)

#define SGE_EXPAND(x) x
#define SGE_CONCAT2(n1, n2) SGE_STRINGIFY_MACRO(SGE_EXPAND(n1)SGE_EXPAND(n2))
#define SGE_CONCAT3(n1, n2, n3) SGE_STRINGIFY_MACRO(EXPAND(n1)SGE_EXPAND(n2)SGE_EXPAND(n3))
#define SGE_CONCAT4(n1, n2, n3,n4) SGE_STRINGIFY_MACRO(EXPAND(n1)SGE_EXPAND(n2)SGE_EXPAND(n3)SGE_EXPAND(n4))
#define SGE_CONCAT5(n1, n2, n3, n4, n5) SGE_STRINGIFY_MACRO(SGE_EXPAND(n1)SGE_EXPAND(n2)SGE_EXPAND(n3)SGE_EXPAND(n4)SGE_EXPAND(n5))

